### ISSUE TITLE
C4::Branch issue

### ISSUE THREAD

**Issue by mtompset** [bywatersolutions/koha-plugin-kitchen-sink#1]
Koha Master and 16.05 builds are unstable.
#     Error:  Can't locate C4/Branch.pm in @INC (you may need to install the C4::Branch module) (@INC contains: /srv/jenkins/workspace/Koha_Master_D8/blib/arch /srv/jenkins/workspace/Koha_Master_D8/blib/lib /srv/jenkins/workspace/Koha_Master_D8 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl . t/db_dependent/.. /home/jenkins/koha_master/var/lib/plugins /home/jenkins/koha_master/var/lib/plugins) at /home/jenkins/koha_master/var/lib/plugins/Koha/Plugin/Com/ByWaterSolutions/KitchenSink.pm line 11.
This is because C4::Branch was obsoleted in newer versions. Is there a patch?

**Comment by kylemhall** [comment]
Resolved! Thanks Jonathan for the pull request!
