### ISSUE TITLE
Highlight new methods for output

### ISSUE THREAD

**Issue by tomascohen** [bywatersolutions/koha-plugin-kitchen-sink#5]
When doing some research to fix [bug 19223](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=19223), I introduced a couple methods: _output_ and _output_html_ which should be highlighted by the time those patches get pushed to master.

The idea is to propose plugin authors to use those instead of crafting their own http headers. This will provide a better user experience as it is less error prone.

**Comment by kylemhall** [comment]
https://github.com/bywatersolutions/koha-plugin-kitchen-sink/commit/b975bb9b8fa981c3c10d3829d8bc3388fb79864a
