### ISSUE TITLE
Undefined subroutine &Koha::Plugin::Com::ByWaterSolutions::KitchenSink::GetMember

### ISSUE THREAD

**Issue by AndrewIsh** [bywatersolutions/koha-plugin-kitchen-sink#7]
A fresh install of the Kitchen Sink plugin is erroring in the following way when clicking on the button:

```
Undefined subroutine &Koha::Plugin::Com::ByWaterSolutions::KitchenSink::GetMember called at /home/koha/koha-dev/var/lib/plugins/Koha/Plugin/Com/ByWaterSolutions/KitchenSink.pm line 437.
```

I can't find a definition of GetMember anywhere in the plugin.

**Comment by Chuckatron** [comment]
So this appears to be due to C4::Members::GetMember & C4::Members::ModPatron no longer existing. The above PR addresses this.

I wonder if it's worth having a tag for the current point in time, pointing out that it will only work with Koha versions < 17.11
